repo_name: TV Android Controller
site_name: TV Android Controller
repo_url: https://github.com/danilofns/tv-android-controller
site_description: "Documentação oficial do TV Android Controller"
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  language: pt-BR
  features:
    - navigation.tabs
  palette:
    primary: custom
    accent: custom

nav:
  - Home: docs/index.md

site_dir: site

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
